version: '3.1'

services:

  sub_reg:
    build:
      context: ./subscription_registration
    container_name: sub_reg
    environment:
      - DEBUG=True
      - DEVELOPMENT_MODE=True
    depends_on:
      - mongo
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./subscription_registration:/app
    ports:
      - "9001:8000"
    networks:
      - micro_net
      
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - micro_data:/data/db
    networks:
      - micro_net

  mongo-express:
    image: mongo-express
    container_name: db_adm
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - micro_net

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbit
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - micro_net

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 9000:6379
    networks:
      - micro_net

volumes:
  micro_data:

networks:
  micro_net:
    driver: bridge
